### ISSUE TITLE
ch07/pig/topics.pig - varaha error

### ISSUE THREAD

**Issue by joechong88** [rjurney/Agile_Data_Code#12] opened 2014-01-05 06:22 UTC
Was executing the above using the command: pig -l /tmp -x local -v -w topics.pig. This was executed within the virtual environment. However, I'm getting an error of "could not instantiate 'varaha.text.TokenizeText' with arguments 'null'".

Pretty sure that varaha has already been compiled and can be located as per topics.pig. Not sure what else to look for. 

Please advise. Thanks.

**Comment by rjurney** [comment] 2014-01-05 19:27
Working on replicating this problem.

**Comment by joechong88** [comment] 2014-01-06 05:51
This is the log of the execution. 

(venv)Joes-MacBook-Air-4:pig joechong$ pig -l /tmp -x local -v -w topics.pig 

2014-01-06 13:50:36,098 [main] INFO  org.apache.pig.Main - Apache Pig version 0.12.1-SNAPSHOT (rUnversioned directory) compiled Dec 19 2013, 23:42:45
2014-01-06 13:50:36,100 [main] INFO  org.apache.pig.Main - Logging error messages to: /private/tmp/pig_1388987436042.log
2014-01-06 13:50:36.359 java[1646:1303] Unable to load realm info from SCDynamicStore
2014-01-06 13:50:37,074 [main] INFO  org.apache.pig.impl.util.Utils - Default bootup file /Users/joechong/.pigbootup not found
2014-01-06 13:50:37,100 [main] INFO  org.apache.pig.tools.parameters.PreprocessorContext - Executing command : echo /usr/local
2014-01-06 13:50:37,239 [main] INFO  org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting to hadoop file system at: file:///
2014-01-06 13:50:38,149 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - created tmp python.cachedir=/var/folders/q6/q5dmstv57bd2hqbg924d5bjr0000gn/T/pig_jython_2775137382646697095
2014-01-06 13:50:41,556 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: funcs._dotProduct
2014-01-06 13:50:41,757 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: funcs.cosineSimilarity
2014-01-06 13:50:41,764 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: funcs.fill_in_blanks
2014-01-06 13:50:41,765 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: funcs.lower
2014-01-06 13:50:41,767 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: funcs.remove_punctuation
2014-01-06 13:50:42,597 [main] ERROR org.apache.pig.PigServer - exception during parsing: Error during parsing. could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
Failed to parse: could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
    at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:198)
    at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1676)
    at org.apache.pig.PigServer$Graph.access$000(PigServer.java:1409)
    at org.apache.pig.PigServer.parseAndBuild(PigServer.java:342)
    at org.apache.pig.PigServer.executeBatch(PigServer.java:367)
    at org.apache.pig.PigServer.executeBatch(PigServer.java:353)
    at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:140)
    at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:202)
    at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:173)
    at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
    at org.apache.pig.Main.run(Main.java:607)
    at org.apache.pig.Main.main(Main.java:156)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
Caused by: java.lang.RuntimeException: could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
    at org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:748)
    at org.apache.pig.newplan.logical.expression.UserFuncExpression.getFieldSchema(UserFuncExpression.java:221)
    at org.apache.pig.newplan.logical.optimizer.FieldSchemaResetter.execute(SchemaResetter.java:264)
    at org.apache.pig.newplan.logical.expression.AllSameExpressionVisitor.visit(AllSameExpressionVisitor.java:143)
    at org.apache.pig.newplan.logical.expression.UserFuncExpression.accept(UserFuncExpression.java:112)
    at org.apache.pig.newplan.ReverseDependencyOrderWalker.walk(ReverseDependencyOrderWalker.java:70)
    at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
    at org.apache.pig.newplan.logical.optimizer.SchemaResetter.visitAll(SchemaResetter.java:67)
    at org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:122)
    at org.apache.pig.newplan.logical.relational.LOGenerate.accept(LOGenerate.java:246)
    at org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
    at org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:114)
    at org.apache.pig.newplan.logical.relational.LOForEach.accept(LOForEach.java:76)
    at org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
    at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
    at org.apache.pig.parser.LogicalPlanBuilder.expandAndResetVisitor(LogicalPlanBuilder.java:408)
    at org.apache.pig.parser.LogicalPlanBuilder.buildForeachOp(LogicalPlanBuilder.java:979)
    at org.apache.pig.parser.LogicalPlanGenerator.foreach_clause(LogicalPlanGenerator.java:15781)
    at org.apache.pig.parser.LogicalPlanGenerator.op_clause(LogicalPlanGenerator.java:1844)
    at org.apache.pig.parser.LogicalPlanGenerator.general_statement(LogicalPlanGenerator.java:1013)
    at org.apache.pig.parser.LogicalPlanGenerator.statement(LogicalPlanGenerator.java:553)
    at org.apache.pig.parser.LogicalPlanGenerator.query(LogicalPlanGenerator.java:421)
    at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:188)
    ... 16 more
Caused by: java.lang.InstantiationException: varaha.text.TokenizeText
    at java.lang.Class.newInstance(Class.java:359)
    at org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:718)
    ... 38 more
2014-01-06 13:50:42,604 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 1200: could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
2014-01-06 13:50:42,605 [main] ERROR org.apache.pig.tools.grunt.Grunt - org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1000: Error during parsing. could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
    at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1689)
    at org.apache.pig.PigServer$Graph.access$000(PigServer.java:1409)
    at org.apache.pig.PigServer.parseAndBuild(PigServer.java:342)
    at org.apache.pig.PigServer.executeBatch(PigServer.java:367)
    at org.apache.pig.PigServer.executeBatch(PigServer.java:353)
    at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:140)
    at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:202)
    at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:173)
    at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
    at org.apache.pig.Main.run(Main.java:607)
    at org.apache.pig.Main.main(Main.java:156)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
Caused by: Failed to parse: could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
    at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:198)
    at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1676)
    ... 15 more
Caused by: java.lang.RuntimeException: could not instantiate 'varaha.text.TokenizeText' with arguments 'null'
    at org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:748)
    at org.apache.pig.newplan.logical.expression.UserFuncExpression.getFieldSchema(UserFuncExpression.java:221)
    at org.apache.pig.newplan.logical.optimizer.FieldSchemaResetter.execute(SchemaResetter.java:264)
    at org.apache.pig.newplan.logical.expression.AllSameExpressionVisitor.visit(AllSameExpressionVisitor.java:143)
    at org.apache.pig.newplan.logical.expression.UserFuncExpression.accept(UserFuncExpression.java:112)
    at org.apache.pig.newplan.ReverseDependencyOrderWalker.walk(ReverseDependencyOrderWalker.java:70)
    at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
    at org.apache.pig.newplan.logical.optimizer.SchemaResetter.visitAll(SchemaResetter.java:67)
    at org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:122)
    at org.apache.pig.newplan.logical.relational.LOGenerate.accept(LOGenerate.java:246)
    at org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
    at org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:114)
    at org.apache.pig.newplan.logical.relational.LOForEach.accept(LOForEach.java:76)
    at org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
    at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
    at org.apache.pig.parser.LogicalPlanBuilder.expandAndResetVisitor(LogicalPlanBuilder.java:408)
    at org.apache.pig.parser.LogicalPlanBuilder.buildForeachOp(LogicalPlanBuilder.java:979)
    at org.apache.pig.parser.LogicalPlanGenerator.foreach_clause(LogicalPlanGenerator.java:15781)
    at org.apache.pig.parser.LogicalPlanGenerator.op_clause(LogicalPlanGenerator.java:1844)
    at org.apache.pig.parser.LogicalPlanGenerator.general_statement(LogicalPlanGenerator.java:1013)
    at org.apache.pig.parser.LogicalPlanGenerator.statement(LogicalPlanGenerator.java:553)
    at org.apache.pig.parser.LogicalPlanGenerator.query(LogicalPlanGenerator.java:421)
    at org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:188)
    ... 16 more
Caused by: java.lang.InstantiationException: varaha.text.TokenizeText
    at java.lang.Class.newInstance(Class.java:359)
    at org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:718)
    ... 38 more

Details also at logfile: /private/tmp/pig_1388987436042.log

**Comment by rjurney** [comment] 2014-01-06 19:56
Haven't forgotten you, working on this.

On Sun, Jan 5, 2014 at 9:51 PM, joechong88 notifications@github.com wrote:

> This is the log of the execution.
> 
> (venv)Joes-MacBook-Air-4:pig joechong$ pig -l /tmp -x local -v -w
> topics.pig
> 
> 2014-01-06 13:50:36,098 [main] INFO org.apache.pig.Main - Apache Pig
> version 0.12.1-SNAPSHOT (rUnversioned directory) compiled Dec 19 2013,
> 23:42:45
> 2014-01-06 13:50:36,100 [main] INFO org.apache.pig.Main - Logging error
> messages to: /private/tmp/pig_1388987436042.log
> 2014-01-06 13:50:36.359 java[1646:1303] Unable to load realm info from
> SCDynamicStore
> 2014-01-06 13:50:37,074 [main] INFO org.apache.pig.impl.util.Utils -
> Default bootup file /Users/joechong/.pigbootup not found
> 2014-01-06 13:50:37,100 [main] INFO
> org.apache.pig.tools.parameters.PreprocessorContext - Executing command :
> echo /usr/local
> 2014-01-06 13:50:37,239 [main] INFO
> org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting
> to hadoop file system at: file:///
> 2014-01-06 13:50:38,149 [main] INFO
> org.apache.pig.scripting.jython.JythonScriptEngine - created tmp
> python.cachedir=/var/folders/q6/q5dmstv57bd2hqbg924d5bjr0000gn/T/pig_jython_2775137382646697095
> 2014-01-06 13:50:41,556 [main] INFO
> org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting
> UDF: funcs.
> 
> _dotProduct 2014-01-06 13:50:41,757 [main] INFO
> org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting
> UDF: funcs.cosineSimilarity 2014-01-06 13:50:41,764 [main] INFO
> org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting
> UDF: funcs.fill_in_blanks
> 2014-01-06 13:50:41,765 [main] INFO
> org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting
> UDF: funcs.lower
> 2014-01-06 13:50:41,767 [main] INFO
> org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting
> UDF: funcs.remove_punctuation
> 2014-01-06 13:50:42,597 [main] ERROR org.apache.pig.PigServer - exception
> during parsing: Error during parsing. could not instantiate
> 'varaha.text.TokenizeText' with arguments 'null'
> Failed to parse: could not instantiate 'varaha.text.TokenizeText' with
> arguments 'null'
> at
> org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:198)
> at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1676)
> at org.apache.pig.PigServer$Graph.access$000(PigServer.java:1409)
> at org.apache.pig.PigServer.parseAndBuild(PigServer.java:342)
> at org.apache.pig.PigServer.executeBatch(PigServer.java:367)
> at org.apache.pig.PigServer.executeBatch(PigServer.java:353)
> at
> org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:140)
> at
> org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:202)
> at
> org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:173)
> at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
> at org.apache.pig.Main.run(Main.java:607)
> at org.apache.pig.Main.main(Main.java:156)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
> Caused by: java.lang.RuntimeException: could not instantiate
> 'varaha.text.TokenizeText' with arguments 'null'
> at
> org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:748)
> at
> org.apache.pig.newplan.logical.expression.UserFuncExpression.getFieldSchema(UserFuncExpression.java:221)
> at
> org.apache.pig.newplan.logical.optimizer.FieldSchemaResetter.execute(SchemaResetter.java:264)
> at
> org.apache.pig.newplan.logical.expression.AllSameExpressionVisitor.visit(AllSameExpressionVisitor.java:143)
> at
> org.apache.pig.newplan.logical.expression.UserFuncExpression.accept(UserFuncExpression.java:112)
> at
> org.apache.pig.newplan.ReverseDependencyOrderWalker.walk(ReverseDependencyOrderWalker.java:70)
> at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
> at
> org.apache.pig.newplan.logical.optimizer.SchemaResetter.visitAll(SchemaResetter.java:67)
> at
> org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:122)
> at
> org.apache.pig.newplan.logical.relational.LOGenerate.accept(LOGenerate.java:246)
> at
> org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
> at
> org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:114)
> at
> org.apache.pig.newplan.logical.relational.LOForEach.accept(LOForEach.java:76)
> at
> org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
> at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
> at
> org.apache.pig.parser.LogicalPlanBuilder.expandAndResetVisitor(LogicalPlanBuilder.java:408)
> at
> org.apache.pig.parser.LogicalPlanBuilder.buildForeachOp(LogicalPlanBuilder.java:979)
> at
> org.apache.pig.parser.LogicalPlanGenerator.foreach_clause(LogicalPlanGenerator.java:15781)
> at
> org.apache.pig.parser.LogicalPlanGenerator.op_clause(LogicalPlanGenerator.java:1844)
> at
> org.apache.pig.parser.LogicalPlanGenerator.general_statement(LogicalPlanGenerator.java:1013)
> at
> org.apache.pig.parser.LogicalPlanGenerator.statement(LogicalPlanGenerator.java:553)
> at
> org.apache.pig.parser.LogicalPlanGenerator.query(LogicalPlanGenerator.java:421)
> at
> org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:188)
> ... 16 more
> Caused by: java.lang.InstantiationException: varaha.text.TokenizeText
> at java.lang.Class.newInstance(Class.java:359)
> at
> org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:718)
> ... 38 more
> 2014-01-06 13:50:42,604 [main] ERROR org.apache.pig.tools.grunt.Grunt -
> ERROR 1200: could not instantiate 'varaha.text.TokenizeText' with arguments
> 'null'
> 2014-01-06 13:50:42,605 [main] ERROR org.apache.pig.tools.grunt.Grunt -
> org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1000: Error
> during parsing. could not instantiate 'varaha.text.TokenizeText' with
> arguments 'null'
> at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1689)
> at org.apache.pig.PigServer$Graph.access$000(PigServer.java:1409)
> at org.apache.pig.PigServer.parseAndBuild(PigServer.java:342)
> at org.apache.pig.PigServer.executeBatch(PigServer.java:367)
> at org.apache.pig.PigServer.executeBatch(PigServer.java:353)
> at
> org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:140)
> at
> org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:202)
> at
> org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:173)
> at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
> at org.apache.pig.Main.run(Main.java:607)
> at org.apache.pig.Main.main(Main.java:156)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
> Caused by: Failed to parse: could not instantiate
> 'varaha.text.TokenizeText' with arguments 'null'
> at
> org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:198)
> at org.apache.pig.PigServer$Graph.parseQuery(PigServer.java:1676)
> ... 15 more
> Caused by: java.lang.RuntimeException: could not instantiate
> 'varaha.text.TokenizeText' with arguments 'null'
> at
> org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:748)
> at
> org.apache.pig.newplan.logical.expression.UserFuncExpression.getFieldSchema(UserFuncExpression.java:221)
> at
> org.apache.pig.newplan.logical.optimizer.FieldSchemaResetter.execute(SchemaResetter.java:264)
> at
> org.apache.pig.newplan.logical.expression.AllSameExpressionVisitor.visit(AllSameExpressionVisitor.java:143)
> at
> org.apache.pig.newplan.logical.expression.UserFuncExpression.accept(UserFuncExpression.java:112)
> at
> org.apache.pig.newplan.ReverseDependencyOrderWalker.walk(ReverseDependencyOrderWalker.java:70)
> at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
> at
> org.apache.pig.newplan.logical.optimizer.SchemaResetter.visitAll(SchemaResetter.java:67)
> at
> org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:122)
> at
> org.apache.pig.newplan.logical.relational.LOGenerate.accept(LOGenerate.java:246)
> at
> org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
> at
> org.apache.pig.newplan.logical.optimizer.SchemaResetter.visit(SchemaResetter.java:114)
> at
> org.apache.pig.newplan.logical.relational.LOForEach.accept(LOForEach.java:76)
> at
> org.apache.pig.newplan.DependencyOrderWalker.walk(DependencyOrderWalker.java:75)
> at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:52)
> at
> org.apache.pig.parser.LogicalPlanBuilder.expandAndResetVisitor(LogicalPlanBuilder.java:408)
> at
> org.apache.pig.parser.LogicalPlanBuilder.buildForeachOp(LogicalPlanBuilder.java:979)
> at
> org.apache.pig.parser.LogicalPlanGenerator.foreach_clause(LogicalPlanGenerator.java:15781)
> at
> org.apache.pig.parser.LogicalPlanGenerator.op_clause(LogicalPlanGenerator.java:1844)
> at
> org.apache.pig.parser.LogicalPlanGenerator.general_statement(LogicalPlanGenerator.java:1013)
> at
> org.apache.pig.parser.LogicalPlanGenerator.statement(LogicalPlanGenerator.java:553)
> at
> org.apache.pig.parser.LogicalPlanGenerator.query(LogicalPlanGenerator.java:421)
> at
> org.apache.pig.parser.QueryParserDriver.parse(QueryParserDriver.java:188)
> ... 16 more
> Caused by: java.lang.InstantiationException: varaha.text.TokenizeText
> at java.lang.Class.newInstance(Class.java:359)
> at
> org.apache.pig.impl.PigContext.instantiateFuncFromSpec(PigContext.java:718)
> ... 38 more
> 
> Details also at logfile: /private/tmp/pig_1388987436042.log
> 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rjurney/Agile_Data_Code/issues/12#issuecomment-31629012
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by rjurney** [comment] 2014-01-06 20:11
While I'm looking for the cause, add this line right after the email LOAD statement:

emails = FILTER emails BY body IS NOT NULL;

and try again.

**Comment by joechong88** [comment] 2014-01-08 01:13
Tried it. Still getting the same error.

**Comment by rjurney** [comment] 2014-01-08 01:18
Will reproduce tonight

On Tuesday, January 7, 2014, joechong88 wrote:

> Tried it. Still getting the same error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rjurney/Agile_Data_Code/issues/12#issuecomment-31797364
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by rjurney** [comment] 2014-01-08 03:47
Reproduced it. What happened is that varaha.text.TokenizeText changed. Verifying now by running topics.pig, but change the define line to this:

DEFINE TokenizeText varaha.text.TokenizeText('1', '1');

And it will work. As soon as I verify this in a test run, I will update the code and you can pull latest. Thanks for your patience in this matter!

**Comment by rjurney** [comment] 2014-01-08 05:21
Resolved by latest push. Pull latest and run topics.pig again.

**Closed as completed by rjurney** 2014-01-08 05:21 UTC
